spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-testing
    username: root
    password: root2005@#
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update